version: '3.6'
services:
  postgres:
    image: postgres
    restart: on-failure
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.9
    ports:
    - "${HASURA_PORT}:8080"
    depends_on:
    - "postgres"
    restart: on-failure
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_AUTH_HOOK: http://envelopes-money:3000/auth/hasura_auth
  envelopes-money:
    image: spiffytech/envelopes.money:beta
    ports:
        - "8001:3000"
    depends_on:
    - "graphql-engine"
    restart: on-failure
    environment:
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1alpha1/graphql
      GRAPHQL_WSS_HOST: ws://localhost:9090/v1/graphql
      HASURA_ADMIN_KEY: myadminsecretkey
      COOKIE_SECRET: pleaseChangeMePleasePlease
      SCRYPT_SALT: correcthorsebatterystaple
      DEBUG: Envelopes.Money:*
volumes:
  db_data:
