version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_AUTH_HOOK: http://hackerbudget:3000/hasura_auth
  hackerbudget:
    image: spiffytech/hackerbudget
    ports:
        - "8001:3000"
    depends_on:
    - "graphql-engine"
    restart: always
    environment:
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1alpha1/graphql
      HASURA_ADMIN_KEY: myadminsecretkey
volumes:
  db_data:
