version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_AUTH_HOOK: http://hackerbudget:3000/hasura_auth
  hackerbudget:
    image: spiffytech/envelopes.money:beta
    ports:
        - "8001:3000"
    depends_on:
    - "graphql-engine"
    restart: always
    environment:
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1alpha1/graphql
      GRAPHQL_HTTP_HOST: http://localhost:8080/v1/graphql
      GRAPHQL_WSS_HOST: ws://localhost:8080/v1/graphql
      HASURA_ADMIN_KEY: myadminsecretkey
      COOKIE_SECRET: pleaseChangeMePleasePlease
      SCRYPT_SALT: correcthorsebatterystaple
      USE_POUCH: "true"
      COUCHDB: http://127.0.0.1:5984
      DEBUG: app
  couch:
    image: couchdb
    restart: always
    volumes:
      - ./couchdb.ini:/opt/couchdb/etc/local.d/docker.ini
      - couchdb_data:/opt/couchdb/data
    ports:
      - 5984:5984
volumes:
  db_data:
  couchdb_data:
