[build]
  base = "client/"
  publish = "client/public/"
  command = "npm run build"
  functions = "client/lambda_built/"

[build.enviroment]
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/env.js"
  to = "/.netlify/functions/env"
  status = 302
